### ISSUE TITLE
Emendas da autora

### ISSUE THREAD

**Issue by suzanasalama** [hedra-editora/mi_valeria_redesguarani#1]
@paulopompermaier mudar todas as menções desse livro: de _índio_ por _indígena_. Cumprir o protocolo de troca de arquivo em 2022_T2/ARQUIVOS

**Comment by paulopompermaier** [comment]
@suzanasalama fiz todas as substituições, com exceção de: 
+ Nomes de instituições (Serviço de Proteção ao Índio, Fundação Nacional do Índio etc.);
+ Nome de obras citadas, documentos, arquivos, notícias de jornal etc. (``Índio é Nós'', ``Índios Guarani
Kaiowá anunciam suicídio coletivo no Mato Grosso do Sul'');
+ Citações diretas dentro de quote, pois não podemos alterar um texto citado...
Tudo certo?

**Comment by suzanasalama** [comment]
@paulopompermaier obrigada! Perfeito comentário. Valéria enviou emendas do artigo dela, vai precisar incluir mais coisas. São pequenas e vou abrir uma nova issue para acompanharmos, tá?
